"use client";

import { useEffect, useState } from "react";
import NavigationPage from "@/components/Home/nav/page";
import { HeroHighlight, Highlight } from "@/components/ui/hero-highlight";

export default function TermsPage() {
  const [active, setActive] = useState("terms");

  useEffect(() => {
    const ids = ["terms", "privacy", "refund", "shipping", "return-policy"];

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActive(entry.target.id);
          }
        });
      },
      {
        rootMargin: "-10% 0px -85% 0px",
        threshold: 0,
      }
    );

    ids.forEach((id) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    // Handle initial hash on load (including legacy hashes)
    let hash = window.location.hash.replace('#', '').replace(/%20/g, ' ');
    if (hash === "Return and Exchange Policy") hash = "return-policy";
    
    if (ids.includes(hash)) {
      setActive(hash);
      setTimeout(() => {
        document.getElementById(hash)?.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    }

    return () => observer.disconnect();
  }, []);

  const navItem = (id: string, label: string) => (
    <a
      href={`#${id}`}
      onClick={(e) => {
        // e.preventDefault();
        setActive(id);
        document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
      }}
      className={`block transition-all duration-300 pl-4 ${
        active === id
          ? "text-black font-semibold border-l-2 border-black"
          : "text-slate-500 hover:text-black"
      }`}
    >
      {label}
    </a>
  );

  return (
    <>
      {/* ===== NAVBAR ===== */}
      <NavigationPage />

      {/* ===== MAIN ===== */}
      <main className="bg-white scroll-smooth"> {/* ⭐ smooth scroll enabled */}
        <div className="max-w-7xl mx-auto px-6 py-16 grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-14">

          {/* ===== SIDEBAR ===== */}
          <aside className="hidden lg:block">
            <div className="sticky top-32 space-y-6">
                
          
              <h3 className="text-xs tracking-[0.2em] text-slate-400 uppercase">
                Lurnexa Legal
              </h3>

       
              <nav className="flex flex-col gap-5 text-sm">
                {navItem("terms", "Terms & Conditions")}
                {navItem("privacy", "Privacy Policy")}
                {navItem("refund", "Refund & Cancellation")}
                {navItem("shipping", "Shipping Policy")}
                {navItem("return-policy", "Return & Exchange Policy")}
              </nav>
            </div>
          </aside>

          {/* ===== CONTENT ===== */}
          <section className="space-y-5 text-slate-700 leading-8">

            <section id="terms" className="scroll-mt-40 min-h-[40vh]">
            
              <h1 className="text-4xl font-bold mb-10 text-slate-900">
                Terms & Conditions
              </h1>
          
              <p className="whitespace-pre-line">
{`This document is an electronic record prepared in accordance with the Information Technology Act, 2000 and
the rules framed thereunder. It is generated by a computer system and does not require any physical or
digital signature. These Terms and Conditions govern the use of the website https://lurnexa.in/journal
and all services offered by Lurnexa Publications.
The website and related services are owned and operated by Lurnexa Publications, having its registered
office at the officially declared business address. All communication related to the platform shall be made
through authorized email and contact channels published on the website.`}
              </p>
        <ul className="list-disc ml-6 mt-4 space-y-2">
                
                <li>By accessing, browsing, registering, or using this platform in any manner, the user agrees to comply with
        these Terms and Conditions. Continued usage shall be treated as unconditional acceptance of these terms.</li>
        <li>Users must provide true, accurate, and complete information. They are responsible for maintaining
        confidentiality of login credentials and all activities under their account.
        </li>
        <li>All content including books, journals, designs, logos, graphics, and digital materials is the exclusive
        intellectual property of Lurnexa Publications. Unauthorized reproduction is prohibited.
        </li>
        <li>Services are provided on an “as is” basis. The company does not guarantee accuracy, reliability, or
        uninterrupted access.
        </li>
        <li>Users shall not engage in unlawful, fraudulent, abusive, or misleading activities. Violations may result in
        suspension or termination.
        </li>
        <li>Payments must be made through authorized gateways. Prices and service charges may change without
        notice.
        </li>
        <li>Lurnexa Publications reserves the right to modify policies, suspend services, or restrict access without prior
        notice.
        </li>
        <li>These terms are governed by Indian law and disputes fall under the jurisdiction of competent courts.
        </li>
        </ul>
            </section>

            <section id="privacy" className="scroll-mt-40 min-h-[40vh]">
              <h2 className="text-2xl font-semibold mb-5 text-slate-900">
                Privacy Policy
              </h2>
              <ul className="list-disc ml-6 mt-4 space-y-2">    
              <li>
            Lurnexa Publications is committed to protecting user privacy and personal information.
            </li>
            <li>Personal data such as name, address, email, phone number, institutional affiliation, payment details, and
            transaction history may be collected during registration and service usage.
            </li>
            <li>
            Information is used for order processing, publishing services, customer support, legal compliance, and
            service improvement. Marketing communication is optional.
            </li>


            <li>Reasonable technical and organizational measures are adopted to protect user data, including encryption
            and secure servers.</li>
            <li>Personal data may be shared with logistics partners, payment processors, technology providers, and
            authorities when required by law.
            </li>

            <li>User data is retained only for business and legal purposes. Users may request correction, access, or deletion
            of data.</li>
            <li>Consent may be withdrawn by written request. Withdrawal may affect service availability.
            </li>
            <li>
            This Privacy Policy may be updated periodically and continued use implies acceptance of revisions.
            </li>
            </ul>
            </section>

            <section id="refund" className="scroll-mt-40 min-h-[40vh]">
              <h2 className="text-2xl font-semibold mb-5 text-slate-900">
                Refund & Cancellation Policy
              </h2>
              <ul className="list-disc ml-6 mt-4 space-y-2">
              
                   <li> This policy governs cancellation and refund of products and services.
                    </li>
                    <li>
                    Cancellation requests are accepted within twenty-four hours of order placement. Once dispatched or
                    customized, cancellation is not permitted.
                    </li>
                    <li>Digital products, subscriptions, and customized publications are non-refundable except for technical failures.</li>
                    <li>Damaged, defective, or misprinted items must be reported within forty-eight hours with supporting evidence.</li>
                    <li>After verification, replacement or refund may be approved at the company’s discretion.
                    </li>
                    <li>Approved refunds are processed within five to seven working days to the original payment method.</li>
                    <li>False or repeated claims may result in account restrictions or suspension.</li>
                    <li> Under any circumstances there will be no refund for article submission fees once an article has been rejected.</li>
</ul>  

            </section>
            <section id="shipping" className="scroll-mt-40 min-h-[40vh]">
              <h2 className="text-2xl font-semibold mb-5 text-slate-900">
                Shipping Policy
              </h2>
              <ul className="list-disc ml-6 mt-4 space-y-2">
             <li>Orders are shipped through registered courier services, India Post, and authorized logistics partners.</li>
            <li>Dispatch is usually completed within three to seven working days after payment confirmation.</li>
            <li>Delivery timelines depend on destination, courier policies, and accessibility.</li>
            <li>The company is not responsible for delays caused by natural disasters, strikes, regulatory actions, or courier
            issues.</li>
            <li>Buyers must provide accurate address details. Incorrect information may cause delivery failure.
            </li>
            <li>Shipping charges are displayed at checkout and are non-refundable.</li>
            <li>Force majeure events may result in unavoidable delays.
            </li>
            </ul>    
        </section>

            <section id="return-policy" className="scroll-mt-40 min-h-[60vh]">
              <h2 className="text-2xl font-semibold mb-5 text-slate-900">
                Return and Exchange Policy
              </h2>
              <ul className="list-disc  ml-6 mt-4 space-y-2">
                <li>Lurnexa Publications offers limited return and exchange facilities.</li>
                <li>Requests must be submitted within seven days of delivery.</li>

                <li>Products must be unused, in original condition, and accompanied by packaging and invoice.
                </li>
                <li>Returns are accepted mainly for damaged, defective, or incorrect items.
                </li>
                <li>Sale or promotional items may not be eligible unless defective.
                </li>
                <li>All returned products undergo quality inspection before approval.</li>
                <li>Misuse of return policy may lead to permanent restrictions.
                </li>
              </ul>
            </section>
          </section>


        </div>
        <div className="h-[60vh] flex items-center justify-center">
          <div className="w-12 h-1.5 bg-slate-100 rounded-full" />
        </div>
      </main>

      {/* ===== FOOTER ===== */}
    </>
  );
}